application: jshint-site
version: 1
runtime: go
api_version: 2

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /about/
  static_files: about.html
  upload: about.html

- url: /options/
  static_files: options.html
  upload: options.html

- url: /src
  static_dir: src

- url: /.+
  script: _go_app